<?php

function hook_block_access(\Drupal\block\Entity\Block $block, $operation, \Drupal\Core\Session\AccountInterface $account) {

  // Prevent displaying the 'Powered by Drupal' block in a region other than the footer.
  if ($operation == 'view' && $block
    ->getPluginId() == 'system_powered_by_block') {
    return AccessResult::forbiddenIf($block
      ->getRegion() != 'footer')
      ->addCacheableDependency($block);
  }

  return AccessResult::neutral();
}